#!/usr/bin/env php
<?php

use Rooty\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('ROOTY_START', microtime(true));
define('ROOTY_CLI', true);

// Register the Composer autoloader.
require __DIR__ . '/vendor/autoload.php';

// ...
$wpLoad = __DIR__ . '/public/wp/wp-load.php';
if (file_exists($wpLoad)) {
    require_once $wpLoad;
}

// Bootstrap Rooty and handle the command.
/** @var Application $app */
$app = require __DIR__ . '/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
